name: Bug report
description: Create a report to help us improve
title: "Bug: "
labels: ["type: bug"]

body:
  - type: textarea
    id: steps
    attributes:
      label: Describe the bug and the steps to reproduce it
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What's the expected behavior?

  - type: textarea
    id: environment
    attributes:
      label: What version of the libraries are you using?
      placeholder: |
        - Build Onchain Apps: [e.g. 0.9.x]
        - Wagmi [e.g. 1.4.x]

