name: Documentation request
description: Suggest a documentation for this project
title: "Documentation Request: "
labels: ["type: documentation"]

body:
  - type: markdown
    attributes:
      value: |
        This issue form is for documentation requests only!
        If you've found a bug, please use [bug_report](/new?template=bug_report.yml)
  - type: textarea
    id: problem
    attributes:
      label: Is your documentation request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. It's not clear when [...]
